{
  "id": "t02_floortile_easy_b",
  "name": "Floortile Easy B",
  "description": "Paint a 3x4 checkerboard with two robots. Settings: rows=3, cols=4, robots=2. Rationale: Adds a column while keeping two-robot column segments.",
  "meta": {
    "domain": "floortile",
    "enable_numeric": true,
    "enable_conditional": false,
    "enable_durations": false,
    "enable_stochastic": false,
    "max_steps": 46,
    "init_fluents": [
      [
        "total-cost",
        [],
        0.0
      ]
    ]
  },
  "objects": {
    "r1": "robot",
    "r2": "robot",
    "tile_0-1": "tile",
    "tile_0-2": "tile",
    "tile_0-3": "tile",
    "tile_0-4": "tile",
    "tile_1-1": "tile",
    "tile_1-2": "tile",
    "tile_1-3": "tile",
    "tile_1-4": "tile",
    "tile_2-1": "tile",
    "tile_2-2": "tile",
    "tile_2-3": "tile",
    "tile_2-4": "tile",
    "tile_3-1": "tile",
    "tile_3-2": "tile",
    "tile_3-3": "tile",
    "tile_3-4": "tile",
    "white": "color",
    "black": "color"
  },
  "static_facts": [
    "(up tile_1-1 tile_0-1)",
    "(down tile_0-1 tile_1-1)",
    "(up tile_1-2 tile_0-2)",
    "(down tile_0-2 tile_1-2)",
    "(up tile_1-3 tile_0-3)",
    "(down tile_0-3 tile_1-3)",
    "(up tile_1-4 tile_0-4)",
    "(down tile_0-4 tile_1-4)",
    "(up tile_2-1 tile_1-1)",
    "(down tile_1-1 tile_2-1)",
    "(up tile_2-2 tile_1-2)",
    "(down tile_1-2 tile_2-2)",
    "(up tile_2-3 tile_1-3)",
    "(down tile_1-3 tile_2-3)",
    "(up tile_2-4 tile_1-4)",
    "(down tile_1-4 tile_2-4)",
    "(up tile_3-1 tile_2-1)",
    "(down tile_2-1 tile_3-1)",
    "(up tile_3-2 tile_2-2)",
    "(down tile_2-2 tile_3-2)",
    "(up tile_3-3 tile_2-3)",
    "(down tile_2-3 tile_3-3)",
    "(up tile_3-4 tile_2-4)",
    "(down tile_2-4 tile_3-4)",
    "(right tile_0-2 tile_0-1)",
    "(left tile_0-1 tile_0-2)",
    "(right tile_0-3 tile_0-2)",
    "(left tile_0-2 tile_0-3)",
    "(right tile_0-4 tile_0-3)",
    "(left tile_0-3 tile_0-4)",
    "(right tile_1-2 tile_1-1)",
    "(left tile_1-1 tile_1-2)",
    "(right tile_1-3 tile_1-2)",
    "(left tile_1-2 tile_1-3)",
    "(right tile_1-4 tile_1-3)",
    "(left tile_1-3 tile_1-4)",
    "(right tile_2-2 tile_2-1)",
    "(left tile_2-1 tile_2-2)",
    "(right tile_2-3 tile_2-2)",
    "(left tile_2-2 tile_2-3)",
    "(right tile_2-4 tile_2-3)",
    "(left tile_2-3 tile_2-4)",
    "(right tile_3-2 tile_3-1)",
    "(left tile_3-1 tile_3-2)",
    "(right tile_3-3 tile_3-2)",
    "(left tile_3-2 tile_3-3)",
    "(right tile_3-4 tile_3-3)",
    "(left tile_3-3 tile_3-4)",
    "(available-color white)",
    "(available-color black)"
  ],
  "init": [
    "(robot-at r1 tile_0-1)",
    "(robot-at r2 tile_0-3)",
    "(robot-has r1 white)",
    "(robot-has r2 black)",
    "(clear tile_0-2)",
    "(clear tile_0-4)",
    "(clear tile_1-1)",
    "(clear tile_1-2)",
    "(clear tile_1-3)",
    "(clear tile_1-4)",
    "(clear tile_2-1)",
    "(clear tile_2-2)",
    "(clear tile_2-3)",
    "(clear tile_2-4)",
    "(clear tile_3-1)",
    "(clear tile_3-2)",
    "(clear tile_3-3)",
    "(clear tile_3-4)"
  ],
  "termination": [
    {
      "name": "goal",
      "when": "(and (painted tile_1-1 white) (painted tile_1-2 black) (painted tile_1-3 white) (painted tile_1-4 black) (painted tile_2-1 black) (painted tile_2-2 white) (painted tile_2-3 black) (painted tile_2-4 white) (painted tile_3-1 white) (painted tile_3-2 black) (painted tile_3-3 white) (painted tile_3-4 black))",
      "outcome": "success",
      "reward": 1.0
    }
  ],
  "reference_plan": [
    "(up r1 tile_0-1 tile_1-1)",
    "(up r1 tile_1-1 tile_2-1)",
    "(paint-up r1 tile_3-1 tile_2-1 white)",
    "(down r1 tile_2-1 tile_1-1)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_2-1 tile_1-1 black)",
    "(down r1 tile_1-1 tile_0-1)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_1-1 tile_0-1 white)",
    "(right r1 tile_0-1 tile_0-2)",
    "(up r1 tile_0-2 tile_1-2)",
    "(up r1 tile_1-2 tile_2-2)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_3-2 tile_2-2 black)",
    "(down r1 tile_2-2 tile_1-2)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_2-2 tile_1-2 white)",
    "(down r1 tile_1-2 tile_0-2)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_1-2 tile_0-2 black)",
    "(up r2 tile_0-3 tile_1-3)",
    "(up r2 tile_1-3 tile_2-3)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_3-3 tile_2-3 white)",
    "(down r2 tile_2-3 tile_1-3)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_2-3 tile_1-3 black)",
    "(down r2 tile_1-3 tile_0-3)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_1-3 tile_0-3 white)",
    "(right r2 tile_0-3 tile_0-4)",
    "(up r2 tile_0-4 tile_1-4)",
    "(up r2 tile_1-4 tile_2-4)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_3-4 tile_2-4 black)",
    "(down r2 tile_2-4 tile_1-4)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_2-4 tile_1-4 white)",
    "(down r2 tile_1-4 tile_0-4)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_1-4 tile_0-4 black)"
  ]
}
