{
  "id": "t06_floortile_hard_b",
  "name": "Floortile Hard B",
  "description": "Paint a 7x7 checkerboard with four robots. Settings: rows=7, cols=7, robots=4. Rationale: Largest grid in the set with long column segments.",
  "meta": {
    "domain": "floortile",
    "enable_numeric": true,
    "enable_conditional": false,
    "enable_durations": false,
    "enable_stochastic": false,
    "max_steps": 188,
    "init_fluents": [
      [
        "total-cost",
        [],
        0.0
      ]
    ]
  },
  "objects": {
    "r1": "robot",
    "r2": "robot",
    "r3": "robot",
    "r4": "robot",
    "tile_0-1": "tile",
    "tile_0-2": "tile",
    "tile_0-3": "tile",
    "tile_0-4": "tile",
    "tile_0-5": "tile",
    "tile_0-6": "tile",
    "tile_0-7": "tile",
    "tile_1-1": "tile",
    "tile_1-2": "tile",
    "tile_1-3": "tile",
    "tile_1-4": "tile",
    "tile_1-5": "tile",
    "tile_1-6": "tile",
    "tile_1-7": "tile",
    "tile_2-1": "tile",
    "tile_2-2": "tile",
    "tile_2-3": "tile",
    "tile_2-4": "tile",
    "tile_2-5": "tile",
    "tile_2-6": "tile",
    "tile_2-7": "tile",
    "tile_3-1": "tile",
    "tile_3-2": "tile",
    "tile_3-3": "tile",
    "tile_3-4": "tile",
    "tile_3-5": "tile",
    "tile_3-6": "tile",
    "tile_3-7": "tile",
    "tile_4-1": "tile",
    "tile_4-2": "tile",
    "tile_4-3": "tile",
    "tile_4-4": "tile",
    "tile_4-5": "tile",
    "tile_4-6": "tile",
    "tile_4-7": "tile",
    "tile_5-1": "tile",
    "tile_5-2": "tile",
    "tile_5-3": "tile",
    "tile_5-4": "tile",
    "tile_5-5": "tile",
    "tile_5-6": "tile",
    "tile_5-7": "tile",
    "tile_6-1": "tile",
    "tile_6-2": "tile",
    "tile_6-3": "tile",
    "tile_6-4": "tile",
    "tile_6-5": "tile",
    "tile_6-6": "tile",
    "tile_6-7": "tile",
    "tile_7-1": "tile",
    "tile_7-2": "tile",
    "tile_7-3": "tile",
    "tile_7-4": "tile",
    "tile_7-5": "tile",
    "tile_7-6": "tile",
    "tile_7-7": "tile",
    "white": "color",
    "black": "color"
  },
  "static_facts": [
    "(up tile_1-1 tile_0-1)",
    "(down tile_0-1 tile_1-1)",
    "(up tile_1-2 tile_0-2)",
    "(down tile_0-2 tile_1-2)",
    "(up tile_1-3 tile_0-3)",
    "(down tile_0-3 tile_1-3)",
    "(up tile_1-4 tile_0-4)",
    "(down tile_0-4 tile_1-4)",
    "(up tile_1-5 tile_0-5)",
    "(down tile_0-5 tile_1-5)",
    "(up tile_1-6 tile_0-6)",
    "(down tile_0-6 tile_1-6)",
    "(up tile_1-7 tile_0-7)",
    "(down tile_0-7 tile_1-7)",
    "(up tile_2-1 tile_1-1)",
    "(down tile_1-1 tile_2-1)",
    "(up tile_2-2 tile_1-2)",
    "(down tile_1-2 tile_2-2)",
    "(up tile_2-3 tile_1-3)",
    "(down tile_1-3 tile_2-3)",
    "(up tile_2-4 tile_1-4)",
    "(down tile_1-4 tile_2-4)",
    "(up tile_2-5 tile_1-5)",
    "(down tile_1-5 tile_2-5)",
    "(up tile_2-6 tile_1-6)",
    "(down tile_1-6 tile_2-6)",
    "(up tile_2-7 tile_1-7)",
    "(down tile_1-7 tile_2-7)",
    "(up tile_3-1 tile_2-1)",
    "(down tile_2-1 tile_3-1)",
    "(up tile_3-2 tile_2-2)",
    "(down tile_2-2 tile_3-2)",
    "(up tile_3-3 tile_2-3)",
    "(down tile_2-3 tile_3-3)",
    "(up tile_3-4 tile_2-4)",
    "(down tile_2-4 tile_3-4)",
    "(up tile_3-5 tile_2-5)",
    "(down tile_2-5 tile_3-5)",
    "(up tile_3-6 tile_2-6)",
    "(down tile_2-6 tile_3-6)",
    "(up tile_3-7 tile_2-7)",
    "(down tile_2-7 tile_3-7)",
    "(up tile_4-1 tile_3-1)",
    "(down tile_3-1 tile_4-1)",
    "(up tile_4-2 tile_3-2)",
    "(down tile_3-2 tile_4-2)",
    "(up tile_4-3 tile_3-3)",
    "(down tile_3-3 tile_4-3)",
    "(up tile_4-4 tile_3-4)",
    "(down tile_3-4 tile_4-4)",
    "(up tile_4-5 tile_3-5)",
    "(down tile_3-5 tile_4-5)",
    "(up tile_4-6 tile_3-6)",
    "(down tile_3-6 tile_4-6)",
    "(up tile_4-7 tile_3-7)",
    "(down tile_3-7 tile_4-7)",
    "(up tile_5-1 tile_4-1)",
    "(down tile_4-1 tile_5-1)",
    "(up tile_5-2 tile_4-2)",
    "(down tile_4-2 tile_5-2)",
    "(up tile_5-3 tile_4-3)",
    "(down tile_4-3 tile_5-3)",
    "(up tile_5-4 tile_4-4)",
    "(down tile_4-4 tile_5-4)",
    "(up tile_5-5 tile_4-5)",
    "(down tile_4-5 tile_5-5)",
    "(up tile_5-6 tile_4-6)",
    "(down tile_4-6 tile_5-6)",
    "(up tile_5-7 tile_4-7)",
    "(down tile_4-7 tile_5-7)",
    "(up tile_6-1 tile_5-1)",
    "(down tile_5-1 tile_6-1)",
    "(up tile_6-2 tile_5-2)",
    "(down tile_5-2 tile_6-2)",
    "(up tile_6-3 tile_5-3)",
    "(down tile_5-3 tile_6-3)",
    "(up tile_6-4 tile_5-4)",
    "(down tile_5-4 tile_6-4)",
    "(up tile_6-5 tile_5-5)",
    "(down tile_5-5 tile_6-5)",
    "(up tile_6-6 tile_5-6)",
    "(down tile_5-6 tile_6-6)",
    "(up tile_6-7 tile_5-7)",
    "(down tile_5-7 tile_6-7)",
    "(up tile_7-1 tile_6-1)",
    "(down tile_6-1 tile_7-1)",
    "(up tile_7-2 tile_6-2)",
    "(down tile_6-2 tile_7-2)",
    "(up tile_7-3 tile_6-3)",
    "(down tile_6-3 tile_7-3)",
    "(up tile_7-4 tile_6-4)",
    "(down tile_6-4 tile_7-4)",
    "(up tile_7-5 tile_6-5)",
    "(down tile_6-5 tile_7-5)",
    "(up tile_7-6 tile_6-6)",
    "(down tile_6-6 tile_7-6)",
    "(up tile_7-7 tile_6-7)",
    "(down tile_6-7 tile_7-7)",
    "(right tile_0-2 tile_0-1)",
    "(left tile_0-1 tile_0-2)",
    "(right tile_0-3 tile_0-2)",
    "(left tile_0-2 tile_0-3)",
    "(right tile_0-4 tile_0-3)",
    "(left tile_0-3 tile_0-4)",
    "(right tile_0-5 tile_0-4)",
    "(left tile_0-4 tile_0-5)",
    "(right tile_0-6 tile_0-5)",
    "(left tile_0-5 tile_0-6)",
    "(right tile_0-7 tile_0-6)",
    "(left tile_0-6 tile_0-7)",
    "(right tile_1-2 tile_1-1)",
    "(left tile_1-1 tile_1-2)",
    "(right tile_1-3 tile_1-2)",
    "(left tile_1-2 tile_1-3)",
    "(right tile_1-4 tile_1-3)",
    "(left tile_1-3 tile_1-4)",
    "(right tile_1-5 tile_1-4)",
    "(left tile_1-4 tile_1-5)",
    "(right tile_1-6 tile_1-5)",
    "(left tile_1-5 tile_1-6)",
    "(right tile_1-7 tile_1-6)",
    "(left tile_1-6 tile_1-7)",
    "(right tile_2-2 tile_2-1)",
    "(left tile_2-1 tile_2-2)",
    "(right tile_2-3 tile_2-2)",
    "(left tile_2-2 tile_2-3)",
    "(right tile_2-4 tile_2-3)",
    "(left tile_2-3 tile_2-4)",
    "(right tile_2-5 tile_2-4)",
    "(left tile_2-4 tile_2-5)",
    "(right tile_2-6 tile_2-5)",
    "(left tile_2-5 tile_2-6)",
    "(right tile_2-7 tile_2-6)",
    "(left tile_2-6 tile_2-7)",
    "(right tile_3-2 tile_3-1)",
    "(left tile_3-1 tile_3-2)",
    "(right tile_3-3 tile_3-2)",
    "(left tile_3-2 tile_3-3)",
    "(right tile_3-4 tile_3-3)",
    "(left tile_3-3 tile_3-4)",
    "(right tile_3-5 tile_3-4)",
    "(left tile_3-4 tile_3-5)",
    "(right tile_3-6 tile_3-5)",
    "(left tile_3-5 tile_3-6)",
    "(right tile_3-7 tile_3-6)",
    "(left tile_3-6 tile_3-7)",
    "(right tile_4-2 tile_4-1)",
    "(left tile_4-1 tile_4-2)",
    "(right tile_4-3 tile_4-2)",
    "(left tile_4-2 tile_4-3)",
    "(right tile_4-4 tile_4-3)",
    "(left tile_4-3 tile_4-4)",
    "(right tile_4-5 tile_4-4)",
    "(left tile_4-4 tile_4-5)",
    "(right tile_4-6 tile_4-5)",
    "(left tile_4-5 tile_4-6)",
    "(right tile_4-7 tile_4-6)",
    "(left tile_4-6 tile_4-7)",
    "(right tile_5-2 tile_5-1)",
    "(left tile_5-1 tile_5-2)",
    "(right tile_5-3 tile_5-2)",
    "(left tile_5-2 tile_5-3)",
    "(right tile_5-4 tile_5-3)",
    "(left tile_5-3 tile_5-4)",
    "(right tile_5-5 tile_5-4)",
    "(left tile_5-4 tile_5-5)",
    "(right tile_5-6 tile_5-5)",
    "(left tile_5-5 tile_5-6)",
    "(right tile_5-7 tile_5-6)",
    "(left tile_5-6 tile_5-7)",
    "(right tile_6-2 tile_6-1)",
    "(left tile_6-1 tile_6-2)",
    "(right tile_6-3 tile_6-2)",
    "(left tile_6-2 tile_6-3)",
    "(right tile_6-4 tile_6-3)",
    "(left tile_6-3 tile_6-4)",
    "(right tile_6-5 tile_6-4)",
    "(left tile_6-4 tile_6-5)",
    "(right tile_6-6 tile_6-5)",
    "(left tile_6-5 tile_6-6)",
    "(right tile_6-7 tile_6-6)",
    "(left tile_6-6 tile_6-7)",
    "(right tile_7-2 tile_7-1)",
    "(left tile_7-1 tile_7-2)",
    "(right tile_7-3 tile_7-2)",
    "(left tile_7-2 tile_7-3)",
    "(right tile_7-4 tile_7-3)",
    "(left tile_7-3 tile_7-4)",
    "(right tile_7-5 tile_7-4)",
    "(left tile_7-4 tile_7-5)",
    "(right tile_7-6 tile_7-5)",
    "(left tile_7-5 tile_7-6)",
    "(right tile_7-7 tile_7-6)",
    "(left tile_7-6 tile_7-7)",
    "(available-color white)",
    "(available-color black)"
  ],
  "init": [
    "(robot-at r1 tile_0-1)",
    "(robot-at r2 tile_0-3)",
    "(robot-at r3 tile_0-5)",
    "(robot-at r4 tile_0-7)",
    "(robot-has r1 white)",
    "(robot-has r2 black)",
    "(robot-has r3 white)",
    "(robot-has r4 black)",
    "(clear tile_0-2)",
    "(clear tile_0-4)",
    "(clear tile_0-6)",
    "(clear tile_1-1)",
    "(clear tile_1-2)",
    "(clear tile_1-3)",
    "(clear tile_1-4)",
    "(clear tile_1-5)",
    "(clear tile_1-6)",
    "(clear tile_1-7)",
    "(clear tile_2-1)",
    "(clear tile_2-2)",
    "(clear tile_2-3)",
    "(clear tile_2-4)",
    "(clear tile_2-5)",
    "(clear tile_2-6)",
    "(clear tile_2-7)",
    "(clear tile_3-1)",
    "(clear tile_3-2)",
    "(clear tile_3-3)",
    "(clear tile_3-4)",
    "(clear tile_3-5)",
    "(clear tile_3-6)",
    "(clear tile_3-7)",
    "(clear tile_4-1)",
    "(clear tile_4-2)",
    "(clear tile_4-3)",
    "(clear tile_4-4)",
    "(clear tile_4-5)",
    "(clear tile_4-6)",
    "(clear tile_4-7)",
    "(clear tile_5-1)",
    "(clear tile_5-2)",
    "(clear tile_5-3)",
    "(clear tile_5-4)",
    "(clear tile_5-5)",
    "(clear tile_5-6)",
    "(clear tile_5-7)",
    "(clear tile_6-1)",
    "(clear tile_6-2)",
    "(clear tile_6-3)",
    "(clear tile_6-4)",
    "(clear tile_6-5)",
    "(clear tile_6-6)",
    "(clear tile_6-7)",
    "(clear tile_7-1)",
    "(clear tile_7-2)",
    "(clear tile_7-3)",
    "(clear tile_7-4)",
    "(clear tile_7-5)",
    "(clear tile_7-6)",
    "(clear tile_7-7)"
  ],
  "termination": [
    {
      "name": "goal",
      "when": "(and (painted tile_1-1 white) (painted tile_1-2 black) (painted tile_1-3 white) (painted tile_1-4 black) (painted tile_1-5 white) (painted tile_1-6 black) (painted tile_1-7 white) (painted tile_2-1 black) (painted tile_2-2 white) (painted tile_2-3 black) (painted tile_2-4 white) (painted tile_2-5 black) (painted tile_2-6 white) (painted tile_2-7 black) (painted tile_3-1 white) (painted tile_3-2 black) (painted tile_3-3 white) (painted tile_3-4 black) (painted tile_3-5 white) (painted tile_3-6 black) (painted tile_3-7 white) (painted tile_4-1 black) (painted tile_4-2 white) (painted tile_4-3 black) (painted tile_4-4 white) (painted tile_4-5 black) (painted tile_4-6 white) (painted tile_4-7 black) (painted tile_5-1 white) (painted tile_5-2 black) (painted tile_5-3 white) (painted tile_5-4 black) (painted tile_5-5 white) (painted tile_5-6 black) (painted tile_5-7 white) (painted tile_6-1 black) (painted tile_6-2 white) (painted tile_6-3 black) (painted tile_6-4 white) (painted tile_6-5 black) (painted tile_6-6 white) (painted tile_6-7 black) (painted tile_7-1 white) (painted tile_7-2 black) (painted tile_7-3 white) (painted tile_7-4 black) (painted tile_7-5 white) (painted tile_7-6 black) (painted tile_7-7 white))",
      "outcome": "success",
      "reward": 1.0
    }
  ],
  "reference_plan": [
    "(up r1 tile_0-1 tile_1-1)",
    "(up r1 tile_1-1 tile_2-1)",
    "(up r1 tile_2-1 tile_3-1)",
    "(up r1 tile_3-1 tile_4-1)",
    "(up r1 tile_4-1 tile_5-1)",
    "(up r1 tile_5-1 tile_6-1)",
    "(paint-up r1 tile_7-1 tile_6-1 white)",
    "(down r1 tile_6-1 tile_5-1)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_6-1 tile_5-1 black)",
    "(down r1 tile_5-1 tile_4-1)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_5-1 tile_4-1 white)",
    "(down r1 tile_4-1 tile_3-1)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_4-1 tile_3-1 black)",
    "(down r1 tile_3-1 tile_2-1)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_3-1 tile_2-1 white)",
    "(down r1 tile_2-1 tile_1-1)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_2-1 tile_1-1 black)",
    "(down r1 tile_1-1 tile_0-1)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_1-1 tile_0-1 white)",
    "(right r1 tile_0-1 tile_0-2)",
    "(up r1 tile_0-2 tile_1-2)",
    "(up r1 tile_1-2 tile_2-2)",
    "(up r1 tile_2-2 tile_3-2)",
    "(up r1 tile_3-2 tile_4-2)",
    "(up r1 tile_4-2 tile_5-2)",
    "(up r1 tile_5-2 tile_6-2)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_7-2 tile_6-2 black)",
    "(down r1 tile_6-2 tile_5-2)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_6-2 tile_5-2 white)",
    "(down r1 tile_5-2 tile_4-2)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_5-2 tile_4-2 black)",
    "(down r1 tile_4-2 tile_3-2)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_4-2 tile_3-2 white)",
    "(down r1 tile_3-2 tile_2-2)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_3-2 tile_2-2 black)",
    "(down r1 tile_2-2 tile_1-2)",
    "(change-color r1 black white)",
    "(paint-up r1 tile_2-2 tile_1-2 white)",
    "(down r1 tile_1-2 tile_0-2)",
    "(change-color r1 white black)",
    "(paint-up r1 tile_1-2 tile_0-2 black)",
    "(up r2 tile_0-3 tile_1-3)",
    "(up r2 tile_1-3 tile_2-3)",
    "(up r2 tile_2-3 tile_3-3)",
    "(up r2 tile_3-3 tile_4-3)",
    "(up r2 tile_4-3 tile_5-3)",
    "(up r2 tile_5-3 tile_6-3)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_7-3 tile_6-3 white)",
    "(down r2 tile_6-3 tile_5-3)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_6-3 tile_5-3 black)",
    "(down r2 tile_5-3 tile_4-3)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_5-3 tile_4-3 white)",
    "(down r2 tile_4-3 tile_3-3)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_4-3 tile_3-3 black)",
    "(down r2 tile_3-3 tile_2-3)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_3-3 tile_2-3 white)",
    "(down r2 tile_2-3 tile_1-3)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_2-3 tile_1-3 black)",
    "(down r2 tile_1-3 tile_0-3)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_1-3 tile_0-3 white)",
    "(right r2 tile_0-3 tile_0-4)",
    "(up r2 tile_0-4 tile_1-4)",
    "(up r2 tile_1-4 tile_2-4)",
    "(up r2 tile_2-4 tile_3-4)",
    "(up r2 tile_3-4 tile_4-4)",
    "(up r2 tile_4-4 tile_5-4)",
    "(up r2 tile_5-4 tile_6-4)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_7-4 tile_6-4 black)",
    "(down r2 tile_6-4 tile_5-4)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_6-4 tile_5-4 white)",
    "(down r2 tile_5-4 tile_4-4)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_5-4 tile_4-4 black)",
    "(down r2 tile_4-4 tile_3-4)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_4-4 tile_3-4 white)",
    "(down r2 tile_3-4 tile_2-4)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_3-4 tile_2-4 black)",
    "(down r2 tile_2-4 tile_1-4)",
    "(change-color r2 black white)",
    "(paint-up r2 tile_2-4 tile_1-4 white)",
    "(down r2 tile_1-4 tile_0-4)",
    "(change-color r2 white black)",
    "(paint-up r2 tile_1-4 tile_0-4 black)",
    "(up r3 tile_0-5 tile_1-5)",
    "(up r3 tile_1-5 tile_2-5)",
    "(up r3 tile_2-5 tile_3-5)",
    "(up r3 tile_3-5 tile_4-5)",
    "(up r3 tile_4-5 tile_5-5)",
    "(up r3 tile_5-5 tile_6-5)",
    "(paint-up r3 tile_7-5 tile_6-5 white)",
    "(down r3 tile_6-5 tile_5-5)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_6-5 tile_5-5 black)",
    "(down r3 tile_5-5 tile_4-5)",
    "(change-color r3 black white)",
    "(paint-up r3 tile_5-5 tile_4-5 white)",
    "(down r3 tile_4-5 tile_3-5)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_4-5 tile_3-5 black)",
    "(down r3 tile_3-5 tile_2-5)",
    "(change-color r3 black white)",
    "(paint-up r3 tile_3-5 tile_2-5 white)",
    "(down r3 tile_2-5 tile_1-5)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_2-5 tile_1-5 black)",
    "(down r3 tile_1-5 tile_0-5)",
    "(change-color r3 black white)",
    "(paint-up r3 tile_1-5 tile_0-5 white)",
    "(right r3 tile_0-5 tile_0-6)",
    "(up r3 tile_0-6 tile_1-6)",
    "(up r3 tile_1-6 tile_2-6)",
    "(up r3 tile_2-6 tile_3-6)",
    "(up r3 tile_3-6 tile_4-6)",
    "(up r3 tile_4-6 tile_5-6)",
    "(up r3 tile_5-6 tile_6-6)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_7-6 tile_6-6 black)",
    "(down r3 tile_6-6 tile_5-6)",
    "(change-color r3 black white)",
    "(paint-up r3 tile_6-6 tile_5-6 white)",
    "(down r3 tile_5-6 tile_4-6)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_5-6 tile_4-6 black)",
    "(down r3 tile_4-6 tile_3-6)",
    "(change-color r3 black white)",
    "(paint-up r3 tile_4-6 tile_3-6 white)",
    "(down r3 tile_3-6 tile_2-6)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_3-6 tile_2-6 black)",
    "(down r3 tile_2-6 tile_1-6)",
    "(change-color r3 black white)",
    "(paint-up r3 tile_2-6 tile_1-6 white)",
    "(down r3 tile_1-6 tile_0-6)",
    "(change-color r3 white black)",
    "(paint-up r3 tile_1-6 tile_0-6 black)",
    "(up r4 tile_0-7 tile_1-7)",
    "(up r4 tile_1-7 tile_2-7)",
    "(up r4 tile_2-7 tile_3-7)",
    "(up r4 tile_3-7 tile_4-7)",
    "(up r4 tile_4-7 tile_5-7)",
    "(up r4 tile_5-7 tile_6-7)",
    "(change-color r4 black white)",
    "(paint-up r4 tile_7-7 tile_6-7 white)",
    "(down r4 tile_6-7 tile_5-7)",
    "(change-color r4 white black)",
    "(paint-up r4 tile_6-7 tile_5-7 black)",
    "(down r4 tile_5-7 tile_4-7)",
    "(change-color r4 black white)",
    "(paint-up r4 tile_5-7 tile_4-7 white)",
    "(down r4 tile_4-7 tile_3-7)",
    "(change-color r4 white black)",
    "(paint-up r4 tile_4-7 tile_3-7 black)",
    "(down r4 tile_3-7 tile_2-7)",
    "(change-color r4 black white)",
    "(paint-up r4 tile_3-7 tile_2-7 white)",
    "(down r4 tile_2-7 tile_1-7)",
    "(change-color r4 white black)",
    "(paint-up r4 tile_2-7 tile_1-7 black)",
    "(down r4 tile_1-7 tile_0-7)",
    "(change-color r4 black white)",
    "(paint-up r4 tile_1-7 tile_0-7 white)"
  ]
}
